name: cipher_frontend
description: C;pher mobile app frontend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_ml_kit: ^0.7.3
  image_picker: ^0.8.5
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/